export const citiesData = [
  {
    city_name: "Alfonso",
    label: "Alfonso",
    city_code: "042101",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Amadeo",
    label: "Amadeo",
    city_code: "042102",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Bacoor City",
    label: "Bacoor",
    city_code: "042103",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Carmona",
    label: "Carmona",
    city_code: "042104",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Cavite City",
    label: "Cavite City",
    city_code: "042105",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "City Of Dasmariñas",
    label: "Dasmariñas",
    city_code: "042106",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "General Trias",
    label: "General Trias",
    city_code: "042108",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Imus City",
    label: "Imus",
    city_code: "042109",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Indang",
    label: "Indang",
    city_code: "042110",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Kawit",
    label: "Kawit",
    city_code: "042111",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Magallanes",
    label: "Magallanes",
    city_code: "042112",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Maragondon",
    label: "Maragondon",
    city_code: "042113",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Mendez",
    label: "Mendez",
    city_code: "042114",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Naic",
    label: "Naic",
    city_code: "042115",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Noveleta",
    label: "Noveleta",
    city_code: "042116",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Rosario",
    label: "Rosario",
    city_code: "042117",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Silang",
    label: "Silang",
    city_code: "042118",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Tagaytay City",
    label: "Tagaytay",
    city_code: "042119",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Tanza",
    label: "Tanza",
    city_code: "042120",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Ternate",
    label: "Ternate",
    city_code: "042121",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Trece Martires City",
    label: "Trece Martires",
    city_code: "042122",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "General Emilio Aguinaldo",
    label: "Gen. Emilio Aguinaldo",
    city_code: "042107",
    province_code: "0421",
    region_desc: "04",
  },
  {
    city_name: "Gen. Mariano Alvarez",
    label: "Gen. Mariano Alvarez",
    city_code: "042123",
    province_code: "0421",
    region_desc: "04",
  },
];
